# Netlify configuration for production deployment
# This file configures headers for production environment

[[headers]]
  for = "/*"
  [headers.values]
    # Security headers for production only
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    
    # CSP for production
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https:;
      worker-src 'self' blob:;
    '''

# Redirect configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
